@extends('layouts.app')
@section('title', 'Guia do laboratório')
@section('content')
<header class="page-heading compact"><div><p class="section-label">QA Moderno · primeira edição</p><h1>O livro guia. O laboratório comprova.</h1><p>Pratique com dados fictícios no seu computador. Não é necessário Docker, Node, servidor externo ou pagamento real.</p></div></header>
<section class="flow-grid">
<article><span>01 · FUNDAMENTOS · CAP. 1–6</span><h3>Observe antes de clicar</h3><p>Explore o catálogo, limites de quantidade (1 a 10), falta de estoque e produto inativo. Use o Kit Essencial QA (R$ 60,00) no relato de bug.</p><a class="text-link" href="{{ route('catalog.index', ['category' => 'Laboratório']) }}">Abrir dados de teste →</a></article>
<article><span>02 · ROTINA · CAP. 7–12</span><h3>Da história à evidência</h3><p>QS-19: crie pedido pendente ou pago, refine critérios e teste o cancelamento. O capítulo 12 mantém um recorte pequeno da página inicial.</p><a class="text-link" href="{{ route('orders.index') }}">Consultar pedidos →</a></article>
<article><span>03 · WEB, API E SQL · CAP. 13–15</span><h3>A mesma informação, três olhares</h3><p>Use DevTools, Postman e SQLite. A API de produtos é aberta apenas no laboratório local para começar sem tokens. A interface usa sessão e permissões.</p><a class="text-link" href="{{ url('/api/v1/products') }}">Abrir API →</a><br><a class="text-link" download href="{{ asset('material/QualityShop.postman_collection.json') }}">Coleção Postman ↓</a><br><a class="text-link" download href="{{ asset('material/consultas-qa.sql') }}">Consultas SQL ↓</a></article>
<article><span>04 · AUTOMAÇÃO E CI · CAP. 16–18</span><h3>Feedback repetível</h3><p>Execute <code>testar.bat</code> no Windows, leia os testes PHPUnit e confira o workflow no repositório. CI remoto depende da publicação no seu GitHub.</p></article>
<article><span>05 · SEGURANÇA · CAP. 19</span><h3>Identidade não é permissão</h3><p>Crie pedido como cliente. Saia e entre com cliente2 para tentar abrir o mesmo endereço: esperado 404. Cliente não acessa administração: esperado 403. Conta bloqueada não entra.</p><a class="text-link" href="{{ route('login') }}">Consultar contas →</a></article>
<article><span>06 · IA E PORTFÓLIO · CAP. 20–21</span><h3>Conclua com julgamento</h3><p>Use IA como apoio, confira sugestões contra regras e resultados e monte seu relatório. Nunca envie senhas reais ou dados de outras pessoas.</p></article>
</section>
<section class="panel form-panel lifecycle-panel"><h2>Regras confirmadas desta edição</h2><ul><li>Quantidade inteira: 1 a 10 por produto, respeitando o estoque. Frete gratuito.</li><li>QA10: 10% em subtotal a partir de R$ 100,00, sem acumular. QAEXPIRADO e códigos diferentes são recusados.</li><li>Estoque é reservado ao criar o pedido, mesmo pendente; cancelar o devolve uma vez. Sem expiração automática: cancele pedidos pendentes quando terminar.</li><li>Fluxo: aguardando pagamento → pago → em separação → enviado → entregue. Cancelamento permitido antes do envio; depois, recusado.</li><li>Pagamento aprovado gera estorno simulado ao cancelar. Falha de estorno mantém pedido e estoque. Reenvio da mesma compra ou aprovação não duplica baixa ou cobrança.</li><li>Operador registra clientes, compra em nome deles e acompanha pedidos; o desconto permitido é o cupom QA10. Gerente acompanha operação e vendas. Administrador também mantém produtos, estoque, contas e perfis.</li></ul></section>
<section class="panel form-panel lifecycle-panel"><h2>Preparar, investigar, restaurar</h2><p>Use <code>configurar.bat</code> uma vez e <code>iniciar.bat</code> a cada sessão. <code>diagnosticar.bat</code> verifica o ambiente. <code>restaurar.bat</code> pede confirmação antes de recriar os dados; exporte suas evidências primeiro.</p><p>QS-BUG-01 fica desativado por padrão. No carrinho, ative a missão, altere a quantidade e produza um relato. O efeito é visual e só vale para sua sessão; os valores persistidos no pedido continuam calculados pelo servidor.</p><details><summary>Consultar resultado esperado do cenário (após investigar)</summary><p>Com o cenário ativo, duas unidades do Kit Essencial mostram total de uma unidade no carrinho. No modo normal, duas unidades somam R$ 120,00; com QA10, o total é R$ 108,00.</p></details><p class="form-note">Limites conscientes: esta edição não implementa banco bancário, gateway, webhooks, frete por transportadora, notas fiscais, e-mails reais nem infraestrutura de produção. Hipóteses de integração do livro permanecem exercícios de refinamento.</p></section>
@endsection
